/**
 * /jtbd-framework/architecture — JTBD Research Lifecycle Diagram
 *
 * Purpose: Static architecture page rendering the full JTBD research lifecycle
 *          as a Mermaid LR graph. Shows how the product landscape and stakeholder
 *          interviews seed the framework, how the framework generates stimulus
 *          materials for workshops and interview probes, how evidence feeds back
 *          iteratively, and how everything converges on the product design brief.
 *
 * Key exports: default export JtbdArchitecturePage (Next.js App Router page)
 *
 * External dependencies:
 *   - mermaid npm package — client-side diagram rendering
 *   - lucide-react — ExternalLink icon for the FigJam button
 *   - BC semantic tokens (via globals.css → dist/css/tokens.css)
 *   - shadcn/ui pattern — bg-background, text-foreground, text-muted-foreground
 *
 * Rendering approach:
 *   Client component only. Mermaid is incompatible with SSR because it directly
 *   manipulates the DOM. We initialise mermaid in a useEffect on mount, call
 *   mermaid.render() to produce an SVG string, and inject that string into a
 *   container div via dangerouslySetInnerHTML. The SVG is then fully static.
 *
 * securityLevel: 'loose' is required so that mermaid can apply the classDef
 *   inline fill/stroke styles. The diagram content is entirely static and
 *   authored here — there is no user-supplied input flowing into the renderer.
 */

"use client";

import { useEffect, useRef, useState } from "react";
import { ExternalLink } from "lucide-react";
import { JtbdNav } from "../_components/JtbdNav";

// ---------------------------------------------------------------------------
// Improvement 4: Single source of truth for diagram colours.
// DIAGRAM_PALETTE drives both the classDef block (injected into the Mermaid
// definition below) and LEGEND_ENTRIES, eliminating the previous duplication
// where hex values were hardcoded independently in two places.
// ---------------------------------------------------------------------------
const DIAGRAM_PALETTE = {
  supply:    { fill: '#DBEAFE', stroke: '#3B82F6', color: '#1E3A5F' },
  seed:      { fill: '#BFDBFE', stroke: '#2563EB', color: '#1E3A5F' },
  framework: { fill: '#EDE9FE', stroke: '#7C3AED', color: '#3B0764' },
  stimulus:  { fill: '#FEF3C7', stroke: '#D97706', color: '#451A03' },
  workshop:  { fill: '#D1FAE5', stroke: '#059669', color: '#064E3B' },
  interview: { fill: '#CFFAFE', stroke: '#0891B2', color: '#0E7490' },
  evidence:  { fill: '#F3F4F6', stroke: '#6B7280', color: '#111827' },
  brief:     { fill: '#FCE7F3', stroke: '#DB2777', color: '#500724' },
} as const

// Improvement 4: Build classDef lines from the palette so the Mermaid diagram
// and the legend can never drift from each other.
const CLASSDEF_LINES = (Object.entries(DIAGRAM_PALETTE) as [string, { fill: string; stroke: string; color: string }][])
  .map(([name, t]) => `  classDef ${name} fill:${t.fill},stroke:${t.stroke},color:${t.color}`)
  .join('\n')

// ---------------------------------------------------------------------------
// Mermaid diagram definition — the full JTBD research lifecycle graph.
// LR layout (left to right) so the supply → framework → stimulus → convergence
// flow reads naturally in reading order.
// The classDef block is generated from DIAGRAM_PALETTE above.
// ---------------------------------------------------------------------------
const DIAGRAM_DEFINITION = `graph LR
${CLASSDEF_LINES}

  subgraph SUPPLY["Supply Track — Product Landscape"]
    L["Product Landscape (159 products)"]:::supply
  end

  subgraph SEED["Initial Demand — Phase 01"]
    SI["Stakeholder Interviews - Round 1 - 7 sessions"]:::seed
  end

  subgraph FRAMEWORK["JTBD Framework Core"]
    JT["Job Taxonomy - 13 jobs"]:::framework
    H["Hirers - 5 types"]:::framework
    JC["Job Chains - 4 templates"]:::framework
    CS["Chain Steps - 195 records - 3 cities x 5 hirers x 13 jobs"]:::framework
    JT -->|"hired by"| H
    JT -->|"sequenced into"| JC
    JC -->|"instantiated per city"| CS
  end

  subgraph STIM["Stimulus Materials Generated by Framework"]
    JCARD["Job Cards"]:::stimulus
    NSTAT["Needs Statements - 12 to 15 job-framed"]:::stimulus
    SCEN["Chain Step Scenarios"]:::stimulus
    GMAP["Gap Maps - supply vs demand per city"]:::stimulus
    HPERS["Hirer Personas"]:::stimulus
  end

  subgraph WORK["Workshop Exercises"]
    W2["Step 2 - Card Sort - Job Ownership Statement"]:::workshop
    W3["Step 3 - Spatial Sort - Product Scope per Surface"]:::workshop
    W4["Step 4 - Dot Vote - Needs Priority List"]:::workshop
    W6["Step 6 - Shortlist - Resident Tool Shortlist"]:::workshop
  end

  subgraph INTER["Interview Probes"]
    EU["End-user Interviews - Residents and civic actors"]:::interview
    IP1["Job Recognition Probe - Do you hire this job"]:::interview
    IP2["Chain Validation Probe - Does this sequence fit your city"]:::interview
    EU --> IP1
    EU --> IP2
  end

  subgraph EV_LOOP["Evidence Feedback Loop"]
    EV["Demand Evidence - validated jobs, weights, new jobs, chain corrections"]:::evidence
  end

  subgraph CONV["Convergence to Brief"]
    UG["Universal Gaps Confirmed - across tiers and cities"]:::brief
    PDB["Product Design Brief - job ownership, product scope, feature priorities, tool shortlist"]:::brief
    UG --> PDB
  end

  L -->|"coded by job"| JT
  L -->|"supply signal per chain step"| CS
  SI -->|"validates jobs, surfaces hirers and city context"| JT

  JT --> JCARD
  JT --> NSTAT
  CS --> SCEN
  CS --> GMAP
  H --> HPERS

  JCARD -->|"Step 2"| W2
  GMAP -->|"Step 3"| W3
  NSTAT -->|"Step 4"| W4
  HPERS -->|"Step 6"| W6
  JCARD -->|"Step 6"| W6

  JCARD --> IP1
  SCEN --> IP2

  W2 --> EV
  W3 --> EV
  W4 --> EV
  W6 --> EV
  IP1 --> EV
  IP2 --> EV

  EV -->|"updates job list and demand signals"| JT
  EV -->|"demand signal update per step"| CS

  CS -->|"gap analysis"| UG
  W2 -->|"ownership locked"| UG
  W3 --> PDB
  W4 --> PDB
  W6 --> PDB`;

// ---------------------------------------------------------------------------
// Colour legend — derived from DIAGRAM_PALETTE so legend and diagram are
// guaranteed to stay in sync (Improvement 4).
// ---------------------------------------------------------------------------
/** A single legend entry describing one node category in the diagram. */
interface LegendEntry {
  label: string;
  fill: string;
  stroke: string;
}

// Improvement 4: LEGEND_ENTRIES now references DIAGRAM_PALETTE directly —
// no duplicated hex literals.
const LEGEND_ENTRIES: LegendEntry[] = [
  { label: "Supply Track",        ...DIAGRAM_PALETTE.supply    },
  // Bug 4 fix: "Initial Demand" uses the distinct `seed` classDef colours
  // (#BFDBFE / #2563EB) instead of the `interview` teal, so the two legend
  // entries are visually distinguishable from "Interview Probes".
  { label: "Initial Demand",      ...DIAGRAM_PALETTE.seed      },
  { label: "Framework Core",      ...DIAGRAM_PALETTE.framework },
  { label: "Stimulus Materials",  ...DIAGRAM_PALETTE.stimulus  },
  { label: "Workshop Exercises",  ...DIAGRAM_PALETTE.workshop  },
  { label: "Interview Probes",    ...DIAGRAM_PALETTE.interview },
  { label: "Evidence Feedback",   ...DIAGRAM_PALETTE.evidence  },
  { label: "Convergence to Brief",...DIAGRAM_PALETTE.brief     },
];

export default function JtbdArchitecturePage() {
  // Improvement 1: useRef initialised once per component lifetime via a null
  // guard. crypto.randomUUID() is guaranteed unique across mount/remount
  // cycles, unlike useId() whose contract doesn't hard-guarantee distinct
  // values on re-mount of the same component instance.
  const diagramIdRef = useRef<string | null>(null)
  if (diagramIdRef.current === null) {
    diagramIdRef.current = 'mermaid-' + crypto.randomUUID()
  }
  const diagramId = diagramIdRef.current

  // Bug 2 fix: svgContainerRef targets the inner div that receives the rendered
  // SVG via dangerouslySetInnerHTML. bindFunctions must be called on a live DOM
  // node after the SVG is inserted, so we need a ref to that specific element.
  const svgContainerRef = useRef<HTMLDivElement>(null);

  // Bug 2 fix: store bindFunctions alongside svgContent so the second useEffect
  // can call it once the SVG string is actually in the DOM.
  const [svgContent, setSvgContent] = useState<string>("");
  const [bindFunctions, setBindFunctions] = useState<
    ((element: Element | null) => void) | undefined
  >(undefined);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [renderError, setRenderError] = useState<string>("");

  // Side effect: initialise mermaid and render the diagram on mount.
  // We import mermaid dynamically to ensure it only runs in the browser.
  // securityLevel: 'loose' is required to allow classDef inline styles.
  // startOnLoad: false because we call render() ourselves for full control.
  useEffect(() => {
    let cancelled = false;

    async function renderDiagram() {
      try {
        // Dynamic import keeps mermaid out of the SSR bundle entirely.
        const mermaid = (await import("mermaid")).default;

        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "loose",
          theme: "default",
          flowchart: {
            curve: "basis",
            padding: 20,
          },
        });

        // Bug 1 fix: pass per-mount diagramId to avoid ID collisions on SPA
        // re-navigation (unmount + remount).
        // Bug 2 fix: destructure bindFunctions from the render result so mermaid
        // can wire up any click handlers or tooltips it registers on the SVG.
        const { svg, bindFunctions: bind } = await mermaid.render(
          diagramId,
          DIAGRAM_DEFINITION
        );

        if (!cancelled) {
          setSvgContent(svg);
          // Store bindFunctions in state so the DOM-insertion effect below can
          // call it after React has committed the SVG to the DOM.
          setBindFunctions(() => bind);
          setIsLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : "Unknown render error";
          setRenderError(message);
          setIsLoading(false);
        }
      }
    }

    renderDiagram();

    // Cleanup: prevent setState calls if the component unmounts before the
    // async render completes (e.g. fast navigation away from the page).
    // Improvement 2: also remove the transient measurement node mermaid injects
    // into <body> as `<div id="d{diagramId}">` — on fast unmount or StrictMode
    // double-invoke this node can be left behind and cause duplicate-ID errors
    // on subsequent renders.
    return () => {
      cancelled = true;
      document.getElementById('d' + diagramId)?.remove();
    };
  }, [diagramId]);

  // Bug 2 fix: second effect runs after svgContent is committed to the DOM.
  // Calls bindFunctions with the SVG container element so mermaid can attach
  // any click handlers or tooltips it registered during the render phase.
  useEffect(() => {
    if (svgContent && bindFunctions && svgContainerRef.current) {
      bindFunctions(svgContainerRef.current);
    }
  }, [svgContent, bindFunctions]);

  return (
    <div className="bg-background text-foreground min-h-screen p-8">
      {/* ── Page header ────────────────────────────────────────────────────── */}
      <div className="mb-8">
        {/* Shared tab navigation — active on "architecture" */}
        <JtbdNav activeTab="architecture" />
        <h1 className="text-3xl font-bold mb-3 mt-4">
          JTBD Framework — Research Lifecycle
        </h1>
        <p className="text-muted-foreground text-base max-w-3xl mb-6">
          How the product landscape and research evidence build the framework,
          generate workshop and interview stimuli, and converge on the product
          design brief.
        </p>

        {/* Action buttons row
            Improvement 5: h-14 (56px) meets JP minimum touch target of 56px.
            "Framework Matrix" button removed — replaced by JtbdNav above. */}
        <div className="flex flex-wrap gap-3">
          {/* External link — opens FigJam board in new tab */}
          <a
            href="https://www.figma.com/board/mU5SS7GeBg58lwjGnmIrgZ"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground h-14 px-4 text-sm font-medium hover:opacity-90 transition-opacity"
          >
            Open in FigJam
            {/* ExternalLink icon signals this opens in a new tab */}
            <ExternalLink className="h-4 w-4" aria-hidden="true" />
          </a>
        </div>
      </div>

      {/* ── Diagram container ───────────────────────────────────────────────
          Improvement 3: replaced the previous single div that combined
          role="img" + aria-live (contradictory across AT implementations)
          with a <figure> / <figcaption> structure:
            - <figure> is an implicit landmark — no role attribute needed
            - inner <div> carries aria-live="polite" and aria-busy so AT
              announces the loading → rendered transition
            - <figcaption className="sr-only"> provides the accessible
              description that role="img" + aria-label previously handled

          overflow-x-auto enables horizontal scroll on narrow viewports so the
          LR diagram is never clipped. min-h ensures the container has space
          while mermaid is initialising.
          ─────────────────────────────────────────────────────────────────── */}
      <figure className="w-full overflow-x-auto rounded-lg border border-border bg-card p-4" style={{ minHeight: "600px" }}>
        <div
          aria-live="polite"
          aria-busy={isLoading}
        >
          {isLoading && !renderError && (
            <div className="flex items-center justify-center h-full min-h-[600px]">
              <p className="text-muted-foreground text-sm">Loading diagram...</p>
            </div>
          )}

          {renderError && (
            <div className="flex items-center justify-center h-full min-h-[600px]">
              <p className="text-destructive text-sm">
                Diagram failed to render: {renderError}
              </p>
            </div>
          )}

          {/* Side effect: inject the rendered SVG string into the DOM.
              dangerouslySetInnerHTML is intentional here — mermaid outputs a
              validated SVG string from our static diagram definition. No user
              input reaches this path.
              Bug 2 fix: ref={svgContainerRef} allows the bindFunctions effect
              above to call mermaid's post-insertion wiring on this exact element. */}
          {!isLoading && !renderError && (
            <div
              ref={svgContainerRef}
              className="w-full"
              dangerouslySetInnerHTML={{ __html: svgContent }}
            />
          )}
        </div>

        {/* Accessible description for the diagram — replaces the former
            aria-label on role="img". Screen readers surface figcaption
            content as the figure's accessible name/description. */}
        <figcaption className="sr-only">
          JTBD research lifecycle diagram — how the product landscape and
          research evidence build the framework, generate workshop and interview
          stimuli, and converge on the product design brief
        </figcaption>
      </figure>

      {/* ── Colour legend ───────────────────────────────────────────────────
          Rendered below the diagram. Each entry shows a coloured dot matching
          the classDef fill/stroke values. Colours are now derived from
          DIAGRAM_PALETTE (Improvement 4) — no separate hardcoded hex values.
          ─────────────────────────────────────────────────────────────────── */}
      <div className="mt-6 flex flex-wrap gap-x-6 gap-y-3">
        {LEGEND_ENTRIES.map((entry) => (
          <div key={entry.label} className="flex items-center gap-2">
            {/* Coloured dot using inline style — hex values come from
                DIAGRAM_PALETTE so they are guaranteed to match classDef.
                These are diagram colours, not UI theme colours, so token
                mapping is not applicable here. */}
            <span
              className="inline-block h-3 w-3 rounded-full flex-shrink-0"
              style={{
                backgroundColor: entry.fill,
                border: `1.5px solid ${entry.stroke}`,
              }}
              aria-hidden="true"
            />
            <span className="text-xs text-muted-foreground">{entry.label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
